# Generated by Django 5.2.5 on 2025-08-25 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(help_text='Введите полное Ф.И.О. клиента', max_length=150, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий', null=True, verbose_name='Комментарий')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите менеджера клиента', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер клиента')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ['full_name'],
                'permissions': [('can_view_client', 'Can view client')],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания рассылки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки')),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('launched', 'Запущена')], default='created', max_length=10)),
                ('clients', models.ManyToManyField(blank=True, help_text='Укажите клиентов рассылки', to='sender.client', verbose_name='Клиенты')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите автора рассылки', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ['created_at', 'finished_at', 'status', 'owner', 'message'],
                'permissions': [('can_view_mailing', 'Can view mailing'), ('can_edit_status', 'Can edit status')],
            },
        ),
        migrations.CreateModel(
            name='AttemptMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки рассылки')),
                ('status', models.CharField(choices=[('successfully', 'Успешно'), ('unsuccessfully', 'Не успешно')], default='successfully', max_length=15)),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите автора рассылки', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рассылки')),
                ('mailing', models.ForeignKey(help_text='Укажите рассылку', on_delete=django.db.models.deletion.CASCADE, to='sender.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'попытка рассылки',
                'verbose_name_plural': 'попытки рассылки',
                'ordering': ['created_at', 'mailing', 'status', 'server_response'],
                'permissions': [('can_view_attempt_mailing', 'Can view attempt mailing')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите тему письма', max_length=150, verbose_name='Тема письма')),
                ('content', models.TextField(blank=True, help_text='Введите содержимое письма', null=True, verbose_name='Содержимое письма')),
                ('owner', models.ForeignKey(blank=True, help_text='Укажите автора сообщения', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['title'],
                'permissions': [('can_view_message', 'Can view message')],
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Укажите сообщение', null=True, on_delete=django.db.models.deletion.CASCADE, to='sender.message', verbose_name='Сообщение'),
        ),
    ]
